import * as pdfjs from 'pdfjs-dist';
import workerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
pdfjs.GlobalWorkerOptions.workerSrc=workerUrl;
export async function openReader(book,{api,toast,onClose,iconsNow,icon,esc}){
let doc,page=book.current_page||1,zoom=1,closed=false,renderTask=null,generation=0,saveChain=Promise.resolve();
const el=document.createElement('div');el.className='reader';el.innerHTML=`<div class="reader-bar"><button class="subtle reader-back">${icon('arrow-left')} 返回书架</button><div class="reader-title">${esc(book.title)}</div><div class="reader-tools"><button class="subtle prev" aria-label="上一页">${icon('chevron-left')}</button><input type="number" min="1" value="${page}" aria-label="跳转页码"><span class="total">/ …</span><button class="subtle next" aria-label="下一页">${icon('chevron-right')}</button><button class="subtle zoom-out" aria-label="缩小">${icon('minus')}</button><span class="zoom-label">100%</span><button class="subtle zoom-in" aria-label="放大">${icon('plus')}</button></div></div><div class="pdf-stage"><canvas></canvas><div class="reader-error">正在打开书页…</div></div><div class="reader-status">阅读进度将自动保存</div>`;document.body.append(el);document.body.classList.add('locked');iconsNow();
const q=s=>el.querySelector(s);const loading=pdfjs.getDocument({url:'/api/books/'+book.id+'/file',cMapUrl:'/pdf-assets/cmaps/',cMapPacked:true,standardFontDataUrl:'/pdf-assets/standard_fonts/',wasmUrl:'/pdf-assets/wasm/'});
function save(){const current=page;saveChain=saveChain.catch(()=>{}).then(()=>api('/'+book.id+'/progress',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({current_page:current})})).then(()=>{if(!closed)q('.reader-status').textContent='已保存 · 第 '+current+' 页'}).catch(()=>{if(!closed)q('.reader-status').textContent='进度保存失败，请检查连接';toast('阅读进度保存失败，请检查后端连接')});}
async function render(){if(!doc||closed)return;const token=++generation;if(renderTask){renderTask.cancel();try{await renderTask.promise}catch{}}const p=await doc.getPage(page);if(closed||token!==generation)return;const stage=q('.pdf-stage'),base=p.getViewport({scale:1}),scale=Math.min((stage.clientWidth-60)/base.width,1.35)*zoom,viewport=p.getViewport({scale}),canvas=q('canvas'),ratio=Math.min(devicePixelRatio||1,2);canvas.width=viewport.width*ratio;canvas.height=viewport.height*ratio;canvas.style.width=viewport.width+'px';canvas.style.height=viewport.height+'px';q('input').value=page;q('.zoom-label').textContent=Math.round(zoom*100)+'%';q('.prev').disabled=page<=1;q('.next').disabled=page>=doc.numPages;q('.zoom-out').disabled=zoom<=.5;q('.zoom-in').disabled=zoom>=2.5;q('.reader-error').hidden=true;renderTask=p.render({canvasContext:canvas.getContext('2d'),viewport,transform:[ratio,0,0,ratio,0,0]});try{await renderTask.promise;if(token===generation)stage.scrollTop=0}catch(e){if(e.name!=='RenderingCancelledException')toast('页面渲染失败：'+e.message)}}
function navigate(value){if(!doc)return;page=Math.max(1,Math.min(doc.numPages,Number(value)||1));render();save()}
q('.prev').onclick=()=>navigate(page-1);q('.next').onclick=()=>navigate(page+1);q('input').onchange=e=>navigate(e.target.value);q('.zoom-in').onclick=()=>{zoom=Math.min(2.5,zoom+.25);render()};q('.zoom-out').onclick=()=>{zoom=Math.max(.5,zoom-.25);render()};
async function back(){if(closed)return;closed=true;renderTask?.cancel();window.removeEventListener('keydown',keys);window.removeEventListener('resize',resize);await saveChain;await loading.destroy();el.remove();document.body.classList.remove('locked');onClose()}
function keys(e){if(e.target.matches('input'))return;if(e.key==='ArrowRight')navigate(page+1);if(e.key==='ArrowLeft')navigate(page-1);if(e.key==='Escape')back()}let resizeTimer;function resize(){clearTimeout(resizeTimer);resizeTimer=setTimeout(render,150)}
q('.reader-back').onclick=back;window.addEventListener('keydown',keys);window.addEventListener('resize',resize);
try{doc=await loading.promise;if(closed)return;page=Math.min(page,doc.numPages);q('.total').textContent='/ '+doc.numPages;q('input').max=doc.numPages;await render();save()}catch(e){if(!closed){q('.reader-error').hidden=false;q('.reader-error').textContent='无法打开 PDF：'+e.message;q('.reader-status').textContent='请返回书架后重试'}}
}
